### ISSUE TITLE
Very Slow

### ISSUE THREAD

**Issue by comunidademagento** [joshuaswarren/magescotch#1]
Hello @joshuaswarren 

First, congratulations for this box vagrant.

Thanks!!!

My host machine is Ubuntu 15.10

See images ...

http://192.168.33.10/magento - work, but very slow.

http://192.168.33.10/magento2 - work, but very slow.

http://192.168.33.10/dev - this environment not work.

![captura de tela de 2015-11-25 14-43-45](https://cloud.githubusercontent.com/assets/7476455/11403399/ba576a80-9383-11e5-973d-b8e9f1aff7e6.png)
![captura de tela de 2015-11-25 14-45-44](https://cloud.githubusercontent.com/assets/7476455/11403397/ba542fdc-9383-11e5-8e3d-da10ef092497.png)
![captura de tela de 2015-11-25 14-46-39](https://cloud.githubusercontent.com/assets/7476455/11403396/ba5183cc-9383-11e5-8b84-386976b394e0.png)
![captura de tela de 2015-11-25 14-47-27](https://cloud.githubusercontent.com/assets/7476455/11403398/ba54a3c2-9383-11e5-9a06-623317d303b1.png)
![captura de tela de 2015-11-25 14-48-40](https://cloud.githubusercontent.com/assets/7476455/11403395/ba502252-9383-11e5-8309-4733167d55a7.png)

**Comment by joshuaswarren** [comment]
Thanks for the great bug report, and for following up with scotch-box - I'll apply those changes they recommended so that everyone can benefit from these improvements.

Also, the dev environment is setup in such a way that you have to add your own files to it for it to work; it's just an empty database and directory for your own dev projects.

After applying the performance improvements scotch-box recommended, how'd everything work for you?
