### ISSUE TITLE
Error When Running Shell Provisioner

### ISSUE THREAD

**Issue by kevinjavitz** [joshuaswarren/magescotch#10]
default: Running: C:/Users/SAGERU~1/AppData/Local/Temp/vagrant-shell20160621-10144-tg31qa.sh
==> default: stdin: is not a tty
==> default: cp: cannot create directory â?~/var/www/public/magento2/var/composer_homeâ?T: File exists
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by joshuaswarren** [comment]
Is there a chance C:/Users/SAGERU~1/AppData/Local/Temp/ or the directory you've checked magescotch out into is on a volume running a case insensitive file system? That script that's trying to run and failing copies the Magento 2 installation out of the base box and into the sync'd directory that syncs with your local environment, so that's my first suspicion - an issue with that file system, especially if it's case insensitive.

**Comment by kevinjavitz** [comment]
yes it is (Windows 10), I guess Magescotch was mainly tested on Mac?

**Comment by joshuaswarren** [comment]
It's developed on Mac, but there's people using it on Windows, Mac and Linux. 

In this case, though, both Mac and Windows use case insensitive file systems, so it's odd to me they're behaving differently. 

Did you check magescotch out into a new, clean folder with nothing else in it? Basically, this is a brand new installation of magescotch? We just released a new version that has some breaking changes from old versions. 

I'll test it out on a Windows 10 machine tomorrow and see what I can see...

**Comment by joshuaswarren** [comment]
The latest version of Magescotch seems to be running fine on Windows 10. If you encounter further errors, let me know. To get the latest version of MageScotch, you'll probably want to check it out into a new directory, and make sure you run 'vagrant box update'.
