### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by weaves81** [joshuaswarren/magescotch#16]
Having an issue with the version of php. In vagrant command line is reporting _PHP 7.0.6-13+donate.sury.org~trusty+1_ and all the correct PHP extensions. Magento Readiness check is reporting _5.6.21-1+donate.sury.org~trusty+4_, missing extensions _xsl, intl_ and _always_populate_raw_post_data 0_. 

Is there anything I need to do to the config to get php 7 to work in the browser as well as the command line?

![screen shot 2016-10-05 at 12 47 03](https://cloud.githubusercontent.com/assets/486750/19112223/8acdc276-8afb-11e6-82c3-775f7710dfd4.png)

**Comment by joshuaswarren** [comment]
This was due to this error in the base box - https://github.com/joshuaswarren/magemalt/issues/2 - I've resolved that, and there should be an updated base box out later today with the fix. 

You'll need to run `vagrant box update` to pull the update down. You're probably running magemalt 2.0.2, and the fix will be in 2.0.3.
