### ISSUE TITLE
VM never comes fully online (OSX El Capitan)

### ISSUE THREAD

**Issue by benmarks** [joshuaswarren/magescotch#24]
Boot timeout, always.  Subsequent attempts to `vagrant ssh` timeout as well.

```
➜  ~ vagrant --version
Vagrant 1.8.5
➜  magescotch git:(master) ✗ vagrant up     
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'creatuity/MageScotchBox'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'creatuity/MageScotchBox' is up to date...
==> default: Setting the name of the VM: magescotch_default_1480018713432_99007
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.
```

**Comment by joshuaswarren** [comment]
Vagrant version, virtual box version and host OS version? I have seen this
on some machines but not all, still trying to narrow it down.

On Nov 24, 2016, at 2:24 PM, Benjamin Marks <notifications@github.com>
wrote:

Boot timeout, always. Subsequent attempts to vagrant ssh timeout as well.

➜  magescotch git:(master) ✗ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'creatuity/MageScotchBox'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'creatuity/MageScotchBox' is up to date...
==> default: Setting the name of the VM: magescotch_default_1480018713432_99007
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/joshuaswarren/magescotch/issues/24>, or mute the thread

**Comment by benmarks** [comment]
Sorry, edited the original post with info (forgot about email-based thread). OSX El Cap & vagrant 1.8.5.

**Comment by benmarks** [comment]
Additional info: increasing `boot_timeout` to 10 minutes does not resolve the issue. Also, the box **does** launch successfully via VirtualBox interface, but never responds to Vagrant.

**Comment by joshuaswarren** [comment]
While I work on tracking this down, will you try upgrading to the latest version of Vagrant (1.8.7)? Ubuntu 16.04 (which is what we're using now) had some issues with older versions of Vagrant, but I can't remember which version fixed it.

Also, what version of VirtualBox do you have installed?

**Comment by benmarks** [comment]
VB was at 5.0.x. Upgrading it and Vagrant to 1.8.7 seems to have done the trick. I did some digging around in the malfunct box and can report that it only had one network adapter, which is different from the functioning box. Even manually running dhclient never yielded a positive result. Abandoned the search after that because it was time for Clemson to destroy The Lesser USC.

Apologies for not being up to date - thanks for the effort!

**Comment by joshuaswarren** [comment]
If I remember what I read in an issue on the main Vagrant repo correctly, Ubuntu 16.04 changed the way networking interfaces are named, and Vagrant had to update to account for that. Knowing that upgrading resolved the issue for you helps a lot, because now I know to add a note to the README saying to make sure you're on Vagrant 1.8.7 or newer. :) 

No worries, and I'm glad you took a break from Vagrant troubleshooting to enjoy the game - I was beginning to worry you were going to work through the entire Thanksgiving weekend!
