### ISSUE TITLE
Z-Ray is expired

### ISSUE THREAD

**Issue by hamdrew** [joshuaswarren/magescotch#3]
Z-Ray does not load when using either Magento application. When visiting [http://192.168.33.10/ZendServer/](http://192.168.33.10/ZendServer/), a notice that the current version of Z-Ray has expired:

![screenshot-192 168 33 10 2016-02-24 15-00-10](https://cloud.githubusercontent.com/assets/4921666/13300828/7e7193b2-db07-11e5-8a77-dd13abdef0ed.png)

I would submit a PR but I'm not sure how to contribute to the Vagrant box using this repository.

Thank you for your work on this. MageScotch has been a very useful tool for us at the University of Wisconsin - Madison to quickly evaluate Magento and start developing for it.

**Comment by joshuaswarren** [comment]
Thanks for your report! I've been having issues with this with Z-Ray, since it's a technology preview and Zend insists on setting an expiration date on it, and then not always remembering to issue an update with a new expiration date before the current one expires.

As a workaround, I've had success with setting the option in the Vagrantfile that tells Vagrant not to sync the VM's clock with your system clock, and then changing the VM's clock back to December. It's not the most elegant solution, but it works.

I am working on an update to the underlying box, which is where I'd upgrade/update Z-Ray, assuming Zend has released a new version. I'll notify you here when that update is available and I'll close this issue then. 

Thanks for the kind words - I wasn't sure how many people were using it, so I'm glad to hear that you have been using it!

**Comment by hamdrew** [comment]
Thanks for the quick response! We are also playing around with updating Z-Ray automatically using a provisioning script.

Are you using Packer to manage the box? If so, would you be adverse to adding the template file to this repository? I would love to be able to fork it to help with contributions and manage our own customization at the UW.

**Comment by joshuaswarren** [comment]
I am managing the box completely manually. It's based on https://github.com/scotch-io/scotch-box (currently v2.0, which is one of the reasons I'm planning a major update to the box soon). I take Scotch Box, which is a great base for PHP development in general, and add in a number of Magento-specific items on top. 

It does make managing the box quite a pain and it makes it impossible to accept PR's to the box itself, so I will look into moving to Packer.

**Comment by hamdrew** [comment]
Let me know if you want any help! I haven't worked with Packer yet, but I've done a lot of provisioning with Puppet and Chef, which is similar.

**Comment by joshuaswarren** [comment]
This is fixed in the latest version of MageScotch. Just a warning, though - I wouldn't upgrade-in-place; I would clone a new copy of this repo and setup a new instance because of some major changes in the past few months. 

If you do decide to upgrade-in-place, you may need to run "vagrant box update" to grab v2 of the base box. 

I did, by the way, switch to our own base box - MageMalt - https://github.com/joshuaswarren/magemalt - that's built using Packer scripts, so if there's further changes to the basebox, feel free to open issues there or submit PRs.
