### ISSUE TITLE
Provisioning fails

### ISSUE THREAD

**Issue by hhirsch** [joshuaswarren/magescotch#30]
Following message:
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp,nolock,vers=3,udp,noatime,actimeo=1 192.168.33.1:/home/linus/magescotch /var/www

Stdout from the command:



Stderr from the command:

mount.nfs: requested NFS version or transport protocol is not supported
```

**Comment by joshuaswarren** [comment]
Most likely this means you either don't have NFS server installed on your computer, or you don't have an NFS server installed that supports NFSv3. You'll want to use NFS v3 because it's much, much faster than older versions for our purposes. 

If you'll let me know what host OS you're running, I can find the appropriate commands for installing NFS v3 and post them here and add them to the readme.

**Comment by hhirsch** [comment]
@joshuaswarren I did not realize I needed NFS. I am on arch linux and on manjaro specifically.

**Comment by joshuaswarren** [comment]
Yeah, without NFS, Vagrant falls back to sharing files between your host machine and the virtual machine via very, very slow methods, so NFS is required. 

Vagrant should handle any configuration changes needed for NFS, so on Arch and Arch-based distributions, installing the package nfs-utils should resolve this issue for you.

**Comment by hhirsch** [comment]
It would be really useful to have a note about that in the README.md.

**Comment by joshuaswarren** [comment]
I've added that to the README. Let me know if there's anything else you need help with as you get MageScotch up and running!

**Comment by hhirsch** [comment]
Thanks. This was a quick and friendly reply.
