### ISSUE TITLE
Permissions not correct out of the box

### ISSUE THREAD

**Issue by vduglued** [joshuaswarren/magescotch#9]
Running on OS X, when I request a Magento 2 category page, I get the following permission errors in zray. Can the permissions be set in the provisioning/install process?

`Directory "/var/www/public/magento2/pub/media/catalog/product/cache" cannot be created Warning!mkdir(): Permission denied`

`Unable to write file into directory /var/www/public/magento2/pub/media/catalog/product/cache/1/small_image/240x300/beff4985b56e3afdbeabfc89641a4582/w/p. Access forbidden.`

`Unable to write file into directory /var/www/public/magento2/pub/media/catalog/product/cache/1/small_image/240x300/beff4985b56e3afdbeabfc89641a4582/w/p. Access forbidden.`

**Comment by joshuaswarren** [comment]
I actually just packaged up a minor update to the box. It's uploading now, then I'm doing a new round of tests. When I do that, I expect to end up packaging up another update as a result of the testing, and I'll make sure this is fixed in that update.

I'm curious - when did you first setup the box? One of the reasons I'm packing up the current update is because on some host setups, the current version doesn't work at all due to some issues with a fancy trick I tried with the synced folders.

**Comment by vduglued** [comment]
Sounds good! I cloned and ran it in the hour before my message.

**Comment by joshuaswarren** [comment]
FYI, this has been resolved. Also, Z-Ray is now only available in https://github.com/joshuaswarren/magescotch5 

This repo - https://github.com/joshuaswarren/magescotch - now contains the PHP 7 based version of MageScotch. Unfortunately, Z-Ray is not yet compatible with PHP 7, so Z-Ray is only available in MageScotch5.
